# 服务器配置
server:
  # 默认端口8080, 如果无需修改默认端口，此配置可不要
  port: 8080
  servlet:
    # 配置servletContextPath路径后，所有的资源访问路径都会加上此前缀
    context-path: /

# 监控管理
management:
  # 端点控制
  endpoints:
    web:
      exposure:
        include: health,info

# spring配置
spring:
  application:
    name: moyu-admin
  profiles:
    active: local
  # mvc配置
  mvc:
    # json转换器
    converters:
      preferred-json-mapper: gson
  # gson格式配置
  gson:
    serialize-nulls: false
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis配置 参考：https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/zh/index.html
mybatis:
  type-aliases-package: com.dodoyd.moyu.admin.domain
  mapper-locations: mapper/*.xml
  #  config-location: classpath:mybatis-config.xml

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.moyu.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml